# Generated by Django 3.2.3 on 2021-06-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210605_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staring_date', models.DateField(default=django.utils.timezone.now)),
                ('starting_time', models.TimeField(default=django.utils.timezone.now)),
                ('class_capacity', models.IntegerField(default=30)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.courses')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scheduling class',
            },
        ),
    ]
