# Generated by Django 3.2.3 on 2021-06-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210605_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to='main.courseinstructor'),
        ),
    ]
