# Generated by Django 3.2.3 on 2021-06-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('main', '0005_courses_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstructor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
