# Generated by Django 3.2.3 on 2021-06-05 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210605_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('staring_date', models.DateField(default=django.utils.timezone.now)),
                ('starting_time', models.TimeField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
