# Generated by Django 3.2.3 on 2021-06-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_events_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(max_length=200, null=True)),
                ('working_date', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scheduling Days',
            },
        ),
        migrations.AddField(
            model_name='schedulingclass',
            name='scheduling_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedulingday'),
        ),
    ]
