# Generated by Django 3.2.3 on 2021-06-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_schedulingday_working_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='created_adt',
            new_name='created_at',
        ),
    ]
