# Generated by Django 3.2.3 on 2021-06-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_created_adt_courses_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingclass',
            name='scheduling_day',
        ),
        migrations.CreateModel(
            name='assignClassToDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_class_per_day', to='main.schedulingclass')),
                ('scheduling_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_day', to='main.schedulingday')),
            ],
            options={
                'verbose_name_plural': 'Assign class to a  Day',
            },
        ),
    ]
