# Generated by Django 3.2.3 on 2021-06-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210613_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulingclass',
            old_name='staring_date',
            new_name='starting_date',
        ),
    ]
