# Generated by Django 3.2.3 on 2021-06-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210605_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Middlename',
            new_name='middlename',
        ),
    ]
